### ISSUE TITLE
Question about input file

### ISSUE THREAD

**Issue by xiaofeiwei1** [Wenjun-Xie/MEME#1]
Dear @Wenjun-Xie,

I would like to ask a question about the input file. I was able to obtain MSA result in a fa form, but I am not sure how to transfer that into the experimental_constraints.txt file as mentioned. Could you please elaborate on that? Thank you so much!

Xiaofei

**Comment by Wenjun-Xie** [comment]
Please check the notebook at https://github.com/Wenjun-Xie/Kemp_eliminase/blob/main/KE07.ipynb for a detailed example.
